name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Setup Solana Keypair
      run: |
        mkdir -p /home/runner/.config/solana
        echo "$SOLANA_KEYPAIR" > /home/runner/.config/solana/id.json
      env:
        SOLANA_KEYPAIR: ${{ secrets.SOLANA_KEYPAIR }}

    - name: Install Anchor
      run: |
        npm install -g @coral-xyz/anchor-cli
        anchor --version

    - name: Install project dependencies
      run: npm install

    - name: Build Anchor program
      run: anchor build

    - name: Run Anchor tests
      run: anchor test
